/**
 * Schema model root owns the logical schema contract: DSL entrypoints, schema/query types,
 * timestamps, and DDL helpers. Normalization, mapping, definition, enum-link resolution, and
 * validation live behind explicit subpaths.
 */
export { asIso8601Timestamp, type Iso8601TimestampString, type TimestampValue } from "./timestamps";
export type {
  AggregateFunction,
  AggregatePlanDecision,
  CheckConstraint,
  ColumnDefinition,
  ColumnValue,
  FilterClauseBase,
  ForeignKeyConstraint,
  LookupPlanDecision,
  NormalizedCalculatedColumnBinding,
  NormalizedColumnBinding,
  NormalizedPhysicalTableBinding,
  NormalizedSourceColumnBinding,
  NormalizedTableBinding,
  NormalizedViewTableBinding,
  NullFilterClause,
  PhysicalDialect,
  PlanRejectDecision,
  PlannedAggregateMetricTerm,
  PlannedAggregateRequest,
  PlannedFilterTerm,
  PlannedLookupRequest,
  PlannedOrderTerm,
  PlannedScanRequest,
  PrimaryKeyConstraint,
  QueryRow,
  ReferentialAction,
  ScalarFilterClause,
  ScanFilterClause,
  ScanFilterOperator,
  ScanOrderBy,
  ScanPlanDecision,
  SchemaBuilder,
  SchemaCalculatedColumnDefinition,
  SchemaColRefToken,
  SchemaColumnLensDefinition,
  SchemaDataEntityHandle,
  SchemaDefinition,
  SchemaDslTableToken,
  SchemaTypedColumnDefinition,
  SchemaValueCoercion,
  SchemaValueCoercionName,
  SchemaViewAggregateMetric,
  SchemaViewAggregateNode,
  SchemaViewEqExpr,
  SchemaViewJoinNode,
  SchemaViewRelNode,
  SchemaViewRelNodeInput,
  SchemaViewScanNode,
  SqlScalarType,
  SqlTypeValue,
  TableAggregateMetric,
  TableAggregateRequest,
  TableColumnDefinition,
  TableColumns,
  TableConstraints,
  TableDefinition,
  TableLookupRequest,
  TableMethods,
  TableMethodsForSchema,
  TableMethodsMap,
  TableName,
  TableRow,
  TableScanRequest,
  UniqueConstraint,
} from "./types";
export { createSchemaBuilder, defineTableMethods, isSchemaBuilder } from "./dsl/builder";
export { toSqlDDL, type SqlDdlOptions } from "./ddl";
