/**
 * Schema is the canonical application-facing surface for building and querying tupl facades.
 * It exposes logical schema APIs plus the stable runtime contracts needed by schema consumers.
 */
export {
  asIso8601Timestamp,
  createSchemaBuilder,
  defineTableMethods,
  getNormalizedTableBinding,
  isNormalizedSourceColumnBinding,
  mapProviderRowsToLogical,
  resolveSchemaLinkedEnums,
  resolveTableColumnDefinition,
  resolveTableProviderResult,
  toSqlDDL,
  validateProviderBindingsResult,
} from "@tupl/schema-model";
export type {
  AggregateFunction,
  AggregatePlanDecision,
  LookupPlanDecision,
  NormalizedColumnBinding,
  PlannedAggregateRequest,
  PlannedLookupRequest,
  PlannedScanRequest,
  QueryRow,
  ScanFilterClause,
  ScanOrderBy,
  ScanPlanDecision,
  SchemaBuilder,
  SchemaColumnLensDefinition,
  SchemaDefinition,
  SqlScalarType,
  TableAggregateMetric,
  TableAggregateRequest,
  TableColumnDefinition,
  TableConstraints,
  TableDefinition,
  TableLookupRequest,
  TableMethods,
  TableMethodsForSchema,
  TableMethodsMap,
  TableName,
  TableScanRequest,
} from "@tupl/schema-model";
export {
  DEFAULT_QUERY_FALLBACK_POLICY,
  DEFAULT_QUERY_GUARDRAILS,
  TuplDiagnosticError,
  createExecutableSchema,
  createExecutableSchemaResult,
} from "@tupl/runtime";
export type {
  ExecutableSchema,
  ExecutableSchemaQueryInput,
  ExecutableSchemaSessionInput,
  ExplainResult,
  QueryExecutionPlan,
  QueryExecutionPlanScope,
  QueryExecutionPlanStep,
  QueryFallbackPolicy,
  QueryGuardrails,
  QuerySession,
  QuerySessionOptions,
  QueryStepEvent,
  QueryStepKind,
  QueryStepOperation,
  QueryStepPhase,
  QueryStepRoute,
  QueryStepState,
  QueryStepStatus,
  QuerySqlOrigin,
} from "@tupl/runtime";
export {
  type TuplProviderBindingError,
  type TuplResult,
  type ConstraintValidationMode,
  type ConstraintValidationOptions,
  type ConstraintViolation,
  type ConstraintViolationType,
  type ValidateTableConstraintsInput,
  validateTableConstraintRows,
} from "@tupl/runtime";
